# Generated by Django 5.2.6 on 2025-09-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj1app', '0002_rename_movie_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Color',
            field=models.CharField(help_text='Car Outer color'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Model',
            field=models.CharField(help_text='Model Number'),
        ),
    ]
