# Generated by Django 5.2.6 on 2025-09-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj1app', '0003_alter_cars_color_alter_cars_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='SNO',
            field=models.CharField(help_text='Car_id', max_length=255),
        ),
    ]
